name: Print Messages on PR Opened

on:
  pull_request:
    branches:
      - main

jobs:
  print-variables-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display environment variable
        run: |
          echo "The environment variable is: $MY_VAR"
        env:
          MY_VAR: ${{ env.MY_VAR }}  # Aquí tomamos la variable desde el entorno de GitHub Actions

      - name: Display secret variable
        run: |
          echo "The secret variable is: $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}  # Aquí tomamos el secreto desde los secretos de GitHub


