name: Print Messages on PR Opened

on:
  pull_request:
    branches:
      - main

jobs:
  print-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment variable
        env:
          MY_VAR: ${{ env.MY_VAR }}
        run: echo "This is the environment variable: $MY_VAR"

      - name: Print secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "This is the secret: $MY_SECRET"

